services:
  - type: web
    name: rag-app
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input
    startCommand: gunicorn rag_app.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: WEB_CONCURRENCY
        value: 2
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
